
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: enabled
  become: yes
  command: systemctl enable elasticsearch.service

- name: restart elasticsearch
  become: yes
  command: systemctl start elasticsearch.service
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
